os: linux
group: beta
language: node_js
node_js: '8'
cache: yarn
before_install:
- export NODE_OPTIONS=–max_old_space_size=4096
install: yarn
script:
- yarn bootstrap
- yarn build
- yarn test
- yarn coverage
