os: linux
group: beta
language: node_js
node_js: '8'
cache: yarn
install: yarn
script:
- yarn bootstrap
- yarn build
- yarn test
- yarn coverage
deploy:
  provider: pages
  local_dir: packages/ap.js/docs
  cleanup: true
  token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: master
