os: linux
group: beta
language: node_js
node_js: '10'
cache: yarn
before_install: export NODE_OPTIONS="--max-old-space-size=4076"
install: yarn
script:
- yarn bootstrap
- yarn build
- yarn test
- yarn coverage
